services:
  backend:
    build: .
    container_name: gadget
    restart: always
    ports:
      - "80:2024"
    environment:
      SPRING_PROFILES_ACTIVE: main
      POSTGRES_USER: gadgetuser
      POSTGRES_PASSWORD: peaksoft
      POSTGRES_DB: postgres
    command: ["java", "-jar", "app.jar", "--server.port=2024"]
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gadgetuser
      POSTGRES_PASSWORD: peaksoft
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
