version: "3.9"
services:
  backend:
    image: your-image-name
    container_name: gadget
    restart: always
    ports:
      - "80:2024"
    environment:
      SPRING_PROFILES_ACTIVE: main
      POSTGRES_DB: postgres
      POSTGRES_USER: gadgetuser
      POSTGRES_PASSWORD: peaksoft
    command: ["java", "-jar", "app.jar", "--server.port=2024"]
    depends_on:
      - database

  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gadgetuser
      POSTGRES_PASSWORD: peaksoft
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
